# Generated by Django 4.2.13 on 2024-08-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
