# Generated by Django 4.2.13 on 2024-08-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_league_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='short_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Short code'),
        ),
    ]
