# Generated by Django 4.2.13 on 2024-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0005_alter_player_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='nationality_id',
            field=models.IntegerField(null=True),
        ),
    ]
