# Generated by Django 4.2.13 on 2024-08-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0006_alter_player_country_id_alter_player_nationality_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('venue_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
                ('home_club_score', models.IntegerField()),
                ('away_club_score', models.IntegerField()),
                ('result_info', models.CharField(blank=True, null=True, verbose_name='Result info')),
                ('match_date', models.DateTimeField()),
                ('length', models.IntegerField(blank=True, null=True)),
                ('away_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='football.club', verbose_name='Away club')),
                ('home_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='football.club', verbose_name='Home club')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='football.round', verbose_name='Round')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixtures', to='football.season', verbose_name='Season')),
            ],
            options={
                'db_table': 'fixture',
            },
        ),
        migrations.CreateModel(
            name='FixtureState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('state', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'fixture_state',
            },
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchState',
        ),
        migrations.AddField(
            model_name='fixture',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.fixturestate', verbose_name='State'),
        ),
    ]
