# Generated by Django 4.2.13 on 2024-08-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0007_fixture_fixturestate_delete_match_delete_matchstate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='code',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
