# Generated by Django 4.2.13 on 2024-08-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0008_position_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='short_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
