# Generated by Django 4.2.13 on 2024-08-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0009_alter_position_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Club type'),
        ),
    ]
