# Generated by Django 4.2.13 on 2024-08-19 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0011_alter_club_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubplayer',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.position'),
        ),
    ]
