# Generated by Django 4.2.13 on 2024-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0012_clubplayer_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayer',
            name='end_date',
            field=models.DateField(null=True, verbose_name='End date'),
        ),
        migrations.AlterField(
            model_name='clubplayer',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Start date'),
        ),
    ]
