# Generated by Django 4.2.13 on 2024-08-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0013_alter_clubplayer_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubplayer',
            name='kit_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
