# Generated by Django 4.2.13 on 2024-08-19 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0015_alter_fixture_away_club_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixture',
            name='venue_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
