# Generated by Django 4.2.13 on 2024-08-22 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0019_premierleaguestatusbyplayer'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='premierleaguestatusbyplayer',
            table='premier_league_player',
        ),
    ]
