# Generated by Django 4.2.13 on 2024-08-22 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0020_alter_premierleaguestatusbyplayer_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='premierleaguestatusbyplayer',
            options={'verbose_name': 'Premier League Player', 'verbose_name_plural': 'Premier League Players'},
        ),
    ]
