# Generated by Django 4.2.13 on 2024-08-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0021_alter_premierleaguestatusbyplayer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='jersey_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Jersey number'),
        ),
    ]
