# Generated by Django 4.2.13 on 2024-08-24 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0022_player_jersey_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SportMonksType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('code', models.CharField(max_length=50, verbose_name='Code')),
                ('developer_name', models.CharField(max_length=100, verbose_name='Developer name')),
                ('model_type', models.CharField(max_length=100, verbose_name='Model type')),
            ],
            options={
                'verbose_name': 'SportMonks Type',
                'verbose_name_plural': 'SportMonks Types',
                'db_table': 'sportmonks_type',
            },
        ),
    ]
