# Generated by Django 4.2.13 on 2024-08-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0023_sportmonkstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sportmonkstype',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code'),
        ),
    ]
