# Generated by Django 4.2.13 on 2024-08-29 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0025_commonplayer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('has_values', models.BooleanField(default=False, verbose_name='Has values')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_statistics', to='football.club', verbose_name='Club')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='football.player', verbose_name='Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.season', verbose_name='Season')),
            ],
            options={
                'verbose_name': 'Player statistic',
                'verbose_name_plural': 'Player statistics',
                'db_table': 'player_statistic',
            },
        ),
        migrations.CreateModel(
            name='PlayerStatisticDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('value', models.JSONField()),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='football.playerstatistic')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.sportmonkstype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Player statistic',
                'verbose_name_plural': 'Player statistics',
                'db_table': 'player_statistic_detail',
            },
        ),
        migrations.CreateModel(
            name='FixtureEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('minute', models.IntegerField(verbose_name='Minute')),
                ('extra_minute', models.IntegerField(blank=True, null=True, verbose_name='Extra minute')),
                ('injured', models.BooleanField(blank=True, null=True, verbose_name='Injured')),
                ('on_bench', models.BooleanField(blank=True, null=True, verbose_name='On bench')),
                ('result', models.CharField(blank=True, null=True, verbose_name='Result')),
                ('info', models.CharField(blank=True, null=True, verbose_name='Info')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='football.fixture', verbose_name='Fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixture_events', to='football.player', verbose_name='Player')),
                ('sub_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.sportmonkstype', verbose_name='Sub type')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.sportmonkstype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Fixture event',
                'verbose_name_plural': 'Fixture events',
                'db_table': 'fixture_event',
            },
        ),
    ]
