# Generated by Django 4.2.13 on 2024-08-29 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_playerstatistic_playerstatisticdetail_fixtureevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureevent',
            name='club',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.club', verbose_name='Club'),
        ),
    ]
