# Generated by Django 4.2.13 on 2024-08-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0027_fixtureevent_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtureevent',
            name='related_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_fixture_events', to='football.player', verbose_name='Related Player'),
        ),
    ]
