# Generated by Django 4.2.13 on 2024-08-30 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0028_fixtureevent_related_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixtureStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('value', models.IntegerField(verbose_name='Value')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('data', models.JSONField(blank=True, null=True, verbose_name='Data')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.club', verbose_name='Club')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='football.fixture', verbose_name='Fixture')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.sportmonkstype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Fixture statistic',
                'verbose_name_plural': 'Fixture statistics',
                'db_table': 'fixture_statistic',
            },
        ),
    ]
