# Generated by Django 4.2.13 on 2024-08-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_fixturestatistic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('remote_id', models.PositiveIntegerField(unique=True, verbose_name='remote id')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.club', verbose_name='Club')),
                ('fixture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='football.fixture', verbose_name='Fixture')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.player', verbose_name='Player')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.sportmonkstype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Fixture lineup',
                'verbose_name_plural': 'Fixture lineups',
                'db_table': 'lineup',
                'unique_together': {('fixture', 'player')},
            },
        ),
    ]
