# Generated by Django 4.2.13 on 2024-08-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0030_lineup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='clubplayer',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='fixtureevent',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='fixturestate',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='fixturestatistic',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='league',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='player',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='playerstatisticdetail',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='position',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='premierleaguestatusbyplayer',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='round',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='season',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
        migrations.AlterField(
            model_name='sportmonkstype',
            name='remote_id',
            field=models.PositiveBigIntegerField(unique=True, verbose_name='remote id'),
        ),
    ]
