# Generated by Django 4.2.13 on 2024-08-31 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0033_remove_club_kit_club_kit_away_club_kit_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixtureevent',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixture_events', to='football.player', verbose_name='Player'),
        ),
    ]
