# Generated by Django 4.2.13 on 2024-08-31 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_tariff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffcase',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tariff_cases', to='finance.tariff'),
        ),
    ]
