# Generated by Django 4.2.13 on 2024-08-31 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_tariffcase_tariff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tariffcase',
            options={'verbose_name': 'Tariff Case', 'verbose_name_plural': 'Tariff Cases'},
        ),
    ]
