# Generated by Django 4.2.13 on 2024-09-03 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0006_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='user',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
