# Generated by Django 4.2.13 on 2024-09-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_remove_tariff_user_alter_subscription_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='tariff',
        ),
        migrations.AddField(
            model_name='subscription',
            name='tariff',
            field=models.ManyToManyField(null=True, related_name='subscription_tariffs', to='finance.tariff'),
        ),
    ]
