# Generated by Django 4.2.13 on 2024-09-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_rename_annual_price_tariff_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tariff',
            field=models.ManyToManyField(blank=True, related_name='subscription_tariffs', to='finance.tariff'),
        ),
    ]
