# Generated by Django 4.2.13 on 2024-09-05 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('football', '0034_alter_fixtureevent_player'),
        ('finance', '0010_alter_subscription_tariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariffcase',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Prices must be in coins.', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='tariffcase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Prices must be in coins.', max_digits=18),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('triple_captain', 'Triple captain'), ('transfer', 'Transfer'), ('join_league', 'League join')], max_length=100),
        ),
        migrations.AlterField(
            model_name='tariffcase',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='tariffcase',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Ordering'),
        ),
        migrations.AlterField(
            model_name='tariffcase',
            name='tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_cases', to='finance.tariff'),
        ),
        migrations.CreateModel(
            name='UserTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Tariff cases price when user bought it.', max_digits=18, null=True)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Tariff cases discount price when user bought it.', max_digits=18, null=True)),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.season', verbose_name='Season')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariffs', to='finance.tariff', verbose_name='Tariff')),
                ('tariff_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariffs', to='finance.tariffcase', verbose_name='Tariff Case')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tariffs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Tariff',
                'verbose_name_plural': 'User Tariff',
                'db_table': 'user_tariff',
            },
        ),
    ]
