# Generated by Django 4.2.13 on 2024-09-07 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0034_alter_fixtureevent_player'),
        ('finance', '0011_tariffcase_discount_price_tariffcase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertariff',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.round', verbose_name='Round'),
        ),
    ]
