# Generated by Django 4.2.13 on 2024-09-07 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0012_usertariff_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Title')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('price', models.DecimalField(decimal_places=2, default=0, help_text='Prices must be in coins.', max_digits=18)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prices must be in coins.', max_digits=18, null=True)),
                ('ordering', models.IntegerField(default=1, verbose_name='Ordering')),
                ('tariff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariff_options', to='finance.tariff')),
            ],
            options={
                'verbose_name': 'Tariff option',
                'verbose_name_plural': 'Tariff options',
                'db_table': 'tariff_option',
            },
        ),
        migrations.CreateModel(
            name='TariffOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('price', models.DecimalField(decimal_places=2, help_text='Prices are in coins.', max_digits=18)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, help_text='Prices are in coins.', max_digits=18, null=True)),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_orders', to='finance.tariff', verbose_name='Tariff')),
                ('tariff_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tariff_orders', to='finance.tariffoption', verbose_name='Tariff option')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tariff_orders', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Tariff Order',
                'verbose_name_plural': 'Tariff Orders',
                'db_table': 'tariff_order',
            },
        ),
        migrations.RemoveField(
            model_name='usertariff',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='usertariff',
            name='price',
        ),
        migrations.RemoveField(
            model_name='usertariff',
            name='tariff_case',
        ),
        migrations.DeleteModel(
            name='TariffCase',
        ),
        migrations.AddField(
            model_name='usertariff',
            name='tariff_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_tariffs', to='finance.tariffoption', verbose_name='Tariff option'),
        ),
    ]
