# Generated by Django 4.2.13 on 2024-09-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_tariffoption_tarifforder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='discount_price',
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='price',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='type',
            field=models.CharField(choices=[('triple_captain', 'Triple captain'), ('transfer', 'Transfer'), ('join_league', 'League join')], max_length=100, unique=True, verbose_name='Type'),
        ),
    ]
