# Generated by Django 4.2.13 on 2024-09-10 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_tarifforder_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
