# Generated by Django 4.2.13 on 2024-09-10 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0016_delete_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('payment_type', models.CharField(choices=[('click', 'Click'), ('payme', 'Payme'), ('uzum_bank', 'Uzum bank')], max_length=100, verbose_name='Payment Type')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_processing', 'Payment processing'), ('success', 'Success'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='pending', max_length=100, verbose_name='Status')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Price')),
                ('coin_amount', models.IntegerField(default=0, verbose_name='Coin Amount')),
            ],
            options={
                'verbose_name': 'Coin Order',
                'verbose_name_plural': 'Coin Orders',
                'db_table': 'coin_order',
            },
        ),
        migrations.CreateModel(
            name='CoinTariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coin_tariff', verbose_name='Image')),
                ('coin_amount', models.IntegerField(default=0, verbose_name='Coin Amount')),
                ('price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Price')),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Discount Price')),
                ('ordering', models.IntegerField(default=1, verbose_name='Ordering')),
            ],
            options={
                'verbose_name': 'Coin Tariff',
                'verbose_name_plural': 'Coin Tariffs',
                'db_table': 'coin_tariff',
            },
        ),
        migrations.CreateModel(
            name='PaymentMerchantRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('header', models.TextField(verbose_name='Header')),
                ('body', models.TextField(verbose_name='Body')),
                ('method', models.CharField(max_length=32, verbose_name='Method')),
                ('response', models.TextField(blank=True, null=True)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Payment Merchant Request Log',
                'verbose_name_plural': 'Payment Merchant Request Logs',
                'db_table': 'payment_merchant_request_log',
            },
        ),
        migrations.AlterField(
            model_name='tarifforder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('payment_processing', 'Payment processing'), ('success', 'Success'), ('canceled', 'Canceled'), ('rejected', 'Rejected')], default='pending', max_length=100, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('click_trans_id', models.CharField(blank=True, max_length=255, null=True)),
                ('click_paydoc_id', models.CharField(blank=True, max_length=255, verbose_name='Номер платежа в системе CLICK')),
                ('merchant_trans_id', models.CharField(blank=True, max_length=255, verbose_name='Номер транзакции в системе магазина')),
                ('amount', models.DecimalField(decimal_places=2, default='0.0', max_digits=9, verbose_name='Сумма оплаты (в сумах)')),
                ('action', models.CharField(blank=True, max_length=255, null=True, verbose_name='Выполняемое действие')),
                ('sign_string', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_time', models.DateTimeField(blank=True, max_length=255, null=True)),
                ('error', models.IntegerField(blank=True, null=True, verbose_name='Код ошибки')),
                ('error_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание ошибки')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('finished', 'Finished'), ('canceled', 'Canceled'), ('error', 'Error')], default='processing', max_length=25, verbose_name='Статус')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.coinorder', verbose_name='Order')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transaction',
            },
        ),
        migrations.AddField(
            model_name='coinorder',
            name='coin_tariff',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coin_orders', to='finance.cointariff', verbose_name='Coin Tariff'),
        ),
        migrations.AddField(
            model_name='coinorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_orders', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
