# Generated by Django 4.2.13 on 2024-09-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('finance', '0017_coinorder_cointariff_paymentmerchantrequestlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointariff',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='cointariff',
            name='title_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Title'),
        ),
    ]
