# Generated by Django 4.2.13 on 2024-09-11 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_cointariff_title_ru_cointariff_title_uz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointariff',
            name='discount_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='uzs', max_digits=18, null=True, verbose_name='Discount Price'),
        ),
        migrations.AlterField(
            model_name='cointariff',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='uzs', max_digits=18, verbose_name='Price'),
        ),
    ]
