from django.db import models
from django.utils.translation import gettext_lazy as _


class SportMonksTypeModelTypeChoices(models.TextChoices):
    EVENT = "event", _("Event")
    HIGHLIGHT = "highlight", _("Highlight")
    INJURY_SUSPENSION = "injury_suspension", _("Injury Suspension")
    LINEUP = "lineup", _("Lineup")
    METADATA = "metadata", _("Metadata")
    PERIOD = "period", _("Period")
    PREDICTION = "prediction", _("Prediction")
    REFEREE = "referee", _("Referee")
    STAGE_TYPE = "stage_type", _("Stage Type")
    STANDING_CORRECTION = "standing_correction", _("Standing Correction")
    STANDING_RULE = "standing_rule", _("Standing Rule")
    STANDINGS = "standings", _("Standings")
    STATISTIC = "statistic", _("Statistic")
    SUB_EVENT = "sub_event", _("Sub Event")
    TIE_BREAKER_RULE = "tie_breaker_rule", _("Tie Breaker Rule")
    TIMELINE = "timeline", _("Timeline")
    TRANSFER = "transfer", _("Transfer")


class FixtureStateChoices(models.TextChoices):
    PENDING = "PENDING", _("Pending")
    PEN_BREAK = "PEN_BREAK", _("Penalties - Break")
    INPLAY_ET_2ND_HALF = "INPLAY_ET_2ND_HALF", _("ET - 2nd Half")
    INPLAY_2ND_HALF = "INPLAY_2ND_HALF", _("2nd Half")
    EXTRA_TIME_BREAK = "EXTRA_TIME_BREAK", _("Extra Time - Break")
    DELETED = "DELETED", _("Deleted")
    AWAITING_UPDATES = "AWAITING_UPDATES", _("Awaiting Updates")
    INTERRUPTED = "INTERRUPTED", _("Interrupted")
    AWARDED = "AWARDED", _("Awarded")
    DELAYED = "DELAYED", _("Delayed")
    ABANDONED = "ABANDONED", _("Abandoned")
    WO = "WO", _("Walk Over")
    TBA = "TBA", _("To Be Announced")
    CANCELLED = "CANCELLED", _("Cancelled")
    SUSPENDED = "SUSPENDED", _("Suspended")
    POSTPONED = "POSTPONED", _("Postponed")
    INPLAY_PENALTIES = "INPLAY_PENALTIES", _("Penalties")
    FT_PEN = "FT_PEN", _("After Penalties")
    AET = "AET", _("After Extra Time")
    INPLAY_ET = "INPLAY_ET", _("Extra Time")
    FT = "FT", _("Full Time")
    BREAK = "BREAK", _("Break")
    HT = "HT", _("Half Time")
    INPLAY_1ST_HALF = "INPLAY_1ST_HALF", _("1st Half")
    NS = "NS", _("Not Started")
