# Generated by Django 4.2.13 on 2024-08-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_phone_number_userotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('User', 'user'), ('Admin', 'admin'), ('Moderator', 'moderator')], default='User'),
        ),
    ]
