# Generated by Django 4.2.13 on 2024-09-05 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='coin_balance',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=18, verbose_name='Coin balance'),
        ),
    ]
