# Generated by Django 4.2.13 on 2024-09-12 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('device_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='Device ID')),
                ('fcm_token', models.CharField(max_length=255, unique=True, verbose_name='FCM token')),
                ('name', models.CharField(max_length=255, verbose_name='Device name')),
                ('device_type', models.CharField(max_length=20, verbose_name='Device type')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User device',
                'verbose_name_plural': 'User devices',
                'db_table': 'user_device',
            },
        ),
    ]
