# Generated by Django 4.2.13 on 2024-09-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='notification',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_ru',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='body_uz',
            field=models.TextField(null=True, verbose_name='body'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='button_name_ru',
            field=models.CharField(blank=True, null=True, verbose_name='route button name'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='button_name_uz',
            field=models.CharField(blank=True, null=True, verbose_name='route button name'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='notificationtemplate',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='notificationtype',
            name='name_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name'),
        ),
    ]
