# Generated by Django 4.2.13 on 2024-09-12 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notification_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_to_all',
            field=models.BooleanField(default=False, verbose_name='Send to all'),
        ),
        migrations.AlterField(
            model_name='notificationtemplate',
            name='type',
            field=models.CharField(choices=[('APP_VERSION_UPDATED', 'App version updated'), ('COIN_ORDER_CREATED', 'Coin order created'), ('COIN_ORDER_PAYMENT_PROCESSING', 'Coin order payment processing'), ('COIN_ORDER_PAYMENT_RECEIVED', 'Coin order payment received'), ('COIN_ORDER_COMPLETED', 'Coin Order Completed'), ('COIN_ORDER_CANCELED', 'Coin Order Canceled'), ('COIN_ORDER_FAILED', 'Coin Order Failed')], max_length=100, verbose_name='Template type'),
        ),
    ]
