# Generated by Django 4.2.13 on 2024-08-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_fantasyleague_remove_league_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='fantasyleague',
            table='fantasy_league',
        ),
    ]
