# Generated by Django 4.2.13 on 2024-08-20 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0016_alter_fixture_venue_id'),
        ('fantasy', '0003_alter_fantasyleague_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('index', models.IntegerField(default=0, verbose_name='Index')),
                ('coordinate_x', models.IntegerField(default=0, verbose_name='Coordinate X')),
                ('coordinate_y', models.IntegerField(default=0, verbose_name='Coordinate Y')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='fantasy.formation', verbose_name='Formation')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.position', verbose_name='Position')),
            ],
            options={
                'verbose_name': 'Formation position',
                'verbose_name_plural': 'Formation positions',
                'db_table': 'formation_position',
            },
        ),
        migrations.CreateModel(
            name='Squad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('formation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasy.formation', verbose_name='Formation')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.round', verbose_name='Round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='squads', to='fantasy.team', verbose_name='Team')),
            ],
            options={
                'db_table': 'fantasy_squad',
            },
        ),
        migrations.CreateModel(
            name='SquadPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasy.teamplayer', verbose_name='Team player')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='fantasy.formationposition', verbose_name='Formation position')),
                ('squad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='fantasy.squad', verbose_name='Squad')),
            ],
            options={
                'db_table': 'fantasy_squad_player',
            },
        ),
    ]
