# Generated by Django 4.2.13 on 2024-08-20 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0007_alter_team_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamplayer',
            name='formation_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasy.formationposition', verbose_name='Formation position'),
        ),
    ]
