# Generated by Django 4.2.13 on 2024-08-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0010_remove_team_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='squadplayer',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='squadplayer',
            name='is_substitution',
            field=models.BooleanField(default=False),
        ),
    ]
