# Generated by Django 4.2.13 on 2024-08-21 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_alter_player_position'),
        ('fantasy', '0012_remove_teamplayer_formation_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('transfer_type', models.CharField(choices=[('sell', 'Sell'), ('buy', 'Buy'), ('swap', 'Swap')], max_length=100, verbose_name='Transfer type')),
                ('fee', models.DecimalField(decimal_places=2, help_text='£(pound sterling)', max_digits=18, verbose_name='Fee')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.player', verbose_name='Player')),
                ('swapped_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.player', verbose_name='Swapped player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='fantasy.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Fantasy transfer',
                'verbose_name_plural': 'Fantasy transfers',
                'db_table': 'fantasy_player_transfer',
            },
        ),
    ]
