# Generated by Django 4.2.13 on 2024-08-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_alter_player_position'),
        ('fantasy', '0013_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamplayer',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_players', to='football.player'),
        ),
    ]
