# Generated by Django 4.2.13 on 2024-08-22 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0018_alter_player_position'),
        ('fantasy', '0014_alter_teamplayer_player'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teamplayer',
            unique_together={('team', 'player')},
        ),
    ]
