# Generated by Django 4.2.13 on 2024-08-22 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0016_transfer_formation_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squadplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasy.teamplayer', verbose_name='Team player'),
        ),
        migrations.AlterUniqueTogether(
            name='squadplayer',
            unique_together={('squad', 'player', 'position')},
        ),
    ]
