# Generated by Django 4.2.13 on 2024-08-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0017_alter_squadplayer_player_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formationposition',
            name='coordinate_x',
        ),
        migrations.RemoveField(
            model_name='formationposition',
            name='coordinate_y',
        ),
        migrations.RemoveField(
            model_name='formationposition',
            name='index',
        ),
        migrations.AddField(
            model_name='formationposition',
            name='ordering',
            field=models.IntegerField(default=1, verbose_name='Ordering'),
        ),
    ]
