# Generated by Django 4.2.13 on 2024-08-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0018_remove_formationposition_coordinate_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formationposition',
            name='is_substitution',
            field=models.BooleanField(default=False, verbose_name='Is substitution'),
        ),
    ]
