# Generated by Django 4.2.13 on 2024-08-22 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0019_formationposition_is_substitution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transfer',
            name='formation_position',
        ),
        migrations.AddField(
            model_name='transfer',
            name='squad_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasy.squadplayer', verbose_name='Squad player'),
        ),
    ]
