# Generated by Django 4.2.13 on 2024-08-23 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0020_remove_transfer_formation_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyleague',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='leagueparticipant',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended')], default='active', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='invite_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
