# Generated by Django 4.2.13 on 2024-08-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0021_fantasyleague_status_leagueparticipant_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fantasyleague',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
