# Generated by Django 4.2.13 on 2024-08-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0022_alter_fantasyleague_end_time_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leagueparticipant',
            unique_together={('league', 'team')},
        ),
    ]
