# Generated by Django 4.2.13 on 2024-08-29 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0026_playerstatistic_playerstatisticdetail_fixtureevent'),
        ('fantasy', '0024_remove_fantasyleague_end_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRoundPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('point', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Points')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.round', verbose_name='Round')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_points', to='fantasy.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Fantasy team round point',
                'verbose_name_plural': 'Fantasy team round points',
                'db_table': 'fantasy_team_round_point',
                'unique_together': {('team', 'round')},
            },
        ),
        migrations.CreateModel(
            name='PlayerRoundPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('point', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Points')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='round_points', to='football.player', verbose_name='Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='football.round', verbose_name='Round')),
            ],
            options={
                'verbose_name': 'Fantasy player round point',
                'verbose_name_plural': 'Fantasy player round points',
                'db_table': 'fantasy_player_round_point',
                'unique_together': {('player', 'round')},
            },
        ),
    ]
