# Generated by Django 4.2.13 on 2024-08-30 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0029_fixturestatistic'),
        ('fantasy', '0025_teamroundpoint_playerroundpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerroundpoint',
            name='assist',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Assist'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='clean_sheet',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='clean sheet'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='goal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Goal'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='goal_conceded',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Goal conceded'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='minutes_played',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Minutes played'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='penalty_miss',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Penalty miss'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='penalty_save',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Penalty save'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='red_card',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Red card'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='saves',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Saves'),
        ),
        migrations.AddField(
            model_name='playerroundpoint',
            name='yellow_card',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Yellow card'),
        ),
        migrations.CreateModel(
            name='SquadPlayerRoundPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('total_point', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Points')),
                ('player_point', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fantasy.playerroundpoint', verbose_name='Player round point')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.round', verbose_name='Round')),
                ('squad_player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='round_point', to='fantasy.squadplayer', verbose_name='Squad player')),
            ],
            options={
                'verbose_name': 'Squad player round point',
                'verbose_name_plural': 'Squad player round points',
                'db_table': 'squad_player_round_point',
            },
        ),
    ]
