# Generated by Django 4.2.13 on 2024-08-30 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0032_alter_club_remote_id_alter_clubplayer_remote_id_and_more'),
        ('fantasy', '0027_remove_playerroundpoint_point_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='squad',
            unique_together={('team', 'round')},
        ),
    ]
