# Generated by Django 4.2.13 on 2024-08-31 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0028_alter_squad_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamroundpoint',
            name='point',
        ),
        migrations.AddField(
            model_name='teamroundpoint',
            name='squad',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='round_point', to='fantasy.squad', verbose_name='Squad'),
        ),
        migrations.AddField(
            model_name='teamroundpoint',
            name='total_point',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Points'),
        ),
    ]
