# Generated by Django 4.2.13 on 2024-09-05 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0029_remove_teamroundpoint_point_teamroundpoint_squad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='team/level/icons/', verbose_name='icon')),
                ('level_point', models.PositiveIntegerField(verbose_name='level point')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
                'db_table': 'level',
            },
        ),
        migrations.CreateModel(
            name='TeamLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted at')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_levels', to='fantasy.level', verbose_name='level')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_levels', to='fantasy.team', verbose_name='Team')),
            ],
            options={
                'verbose_name': 'Team level',
                'verbose_name_plural': 'Team levels',
                'db_table': 'team_level',
            },
        ),
    ]
