# Generated by Django 4.2.13 on 2024-09-07 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0034_alter_fixtureevent_player'),
        ('fantasy', '0031_leaguememberroundpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.round', verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='fantasyleague',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('finished', 'Finished')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
