# Generated by Django 4.2.13 on 2024-09-09 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0034_alter_fixtureevent_player'),
        ('fantasy', '0032_transfer_round_alter_fantasyleague_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerroundpoint',
            name='fixture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='football.fixture', verbose_name='Fixture'),
        ),
    ]
